easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Article
       - App\Entity\Articletype
       - App\Entity\Skill
       - App\Entity\Course
       - App\Entity\Coursegroup
       - App\Entity\Videos
       - App\Entity\Contacts
       - App\Entity\Qa
       - App\Entity\Footericons